// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaatbkygzjeauzezbllm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhYXRia3lnemplYXV6ZXpibGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTgxNDIsImV4cCI6MjA3MTk3NDE0Mn0.njJYlS9R9T-8JvahgOBZbSuTotpnlTuAkVtwc3ihG6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});